### ISSUE TITLE
65b bug on windows?

### ISSUE THREAD

**Issue by Completeandtotalidiotalsolazy** [LostRuins/llamacpp-for-kobold#5]
can load 30b on my system fine, works great! Appreciate the program! Just wanted to report a bug. Or maybe its not a bug and I just messed something up lol

line 50 :     ret = handle.load_model(inputs)

it looks like its just loading the model?

![1679787836584321](https://user-images.githubusercontent.com/128942217/227748225-bd902ea5-6942-4f5b-8354-4bcfc1c7ec94.jpg)

**Comment by LostRuins** [comment]
Could it be that you've run out of RAM? Does 65b work fine with the normal llama.cpp and main.exe?  I heard there was a bug loading 65b there too, and llamacpp-for-kobold uses the same libraries behind the scenes - but it should have been fixed in the newest version. Unfortunately I don't have enough RAM on my local system to test 65b myself.

**Comment by rabidcopy** [comment]
Should likely be fixed by https://github.com/ggerganov/llama.cpp/commit/6f1ee4b640912211a4b07965c585d327e32e734d whenever it gets merged over here.

**Comment by LostRuins** [comment]
Am closing this issue as I believe this bug is resolved in the newest version. If there are further issues, feel free to open a new issue.
